TeotiShopy/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from home import urls as UrlsHome
from actividades import urls as UrlsActividades
from eventos import urls as UrlsEventos
from alojamiento import urls as UrlsAlojamientos
from blog import urls as UrlsBlog
from restaurantes import urls as UrlsRestaurantes
from servicios import urls as UrlsServicios
from tour import urls as UrlsTour
from shop import urls as UrlsShop
from ruta import urls as UrlsRuta

from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include(UrlsBlog,namespace="blog")),
    url(r'^',include(UrlsHome,namespace="home")),
    url(r'^',include(UrlsEventos,namespace="eventos")),
    url(r'^',include(UrlsActividades,namespace="actividades")),
    url(r'^',include(UrlsAlojamientos,namespace="alojamientos")), 
    url(r'^',include(UrlsRestaurantes,namespace="restaurantes")),
    url(r'^',include(UrlsServicios,namespace="servicios")),
    url(r'^',include(UrlsTour,namespace="tours")),
    url(r'^',include(UrlsShop,namespace="shop")),
    url(r'^',include(UrlsRuta,namespace="ruta")),        
    url(
    	regex=r'^media/(?P<path>.*)$',
    	view=serve,
    	kwargs = {'document_root':settings.MEDIA_ROOT}),
]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.PostList.as_view(), name='post_list'),
	url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.PostList.as_view(), name="post_list_by_tag"),
	url(r'^list/$', views.PostListView.as_view(), name='post_list_view'),
	url(r'^(?P<post>[-\w]+)/$', views.PostDetailView.as_view(), name="post_detail"),
	url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.PostDetail.as_view(), name="post_detail"),
	url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/(?P<ready>\d+)/$', views.PostDetail.as_view(), name="post_detail_ready"),
	url(r'^(?P<post_id>\d+)/share/$', views.SentEmailView.as_view(), name="post_share"),
	url(r'^(?P<post_id>\d+)/(?P<conf>\d+)/share/$', views.SentEmailView.as_view(), name="post_share_conf"),
]

eventos/urls.py
from django.conf.urls import url
from . import views

urlpatterns =[
	url(r'^evento-list/$',views.Evento_List.as_view(), name="evento_list"),
	url(r'^evento-list/(?P<categoria_slug>[-\w]+)/$',views.Evento_List.as_view(),name="evento_list_by_categoria"),
	url(r'^evento-detail/(?P<slug>[-\w]+)/$',views.Evento_Detail.as_view(), name="evento_detail"),
	# url(r'^evento-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$',views.Evento_Detail.as_view(), name="evento_detail"),
]	

home/urls.py
from django.conf.urls import url
from . import views

urlpatterns =[
	url(r'^$',views.Home.as_view(),name="home"),
	url(r'^tienda/$',views.TiendaView.as_view(),name="tienda"),
	url(r'^prestadores-servicio/$',views.PrestadoresView.as_view(), name = "prestadores"),
	url(r'^sitios-web/$',views.SiteWeb.as_view(), name = "siteweb"),
]

ruta/urls.py
from django.conf.urls import url 
from . import views

urlpatterns = [
	url(r'^lugar-list/$',views.Lugar_List.as_view(), name="lugar_list"),
	url(r'^lugar-detail/(?P<slug>[-\w]+)/$',views.Lugar_Detail.as_view(), name="lugar_detail"),
]

shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^product-list/$',views.ProductList.as_view(),name="list-product"),
]

tour/urls.py
from django.conf.urls import url
from . import views

urlpatterns =[
	url(r'^tour-list/$',views.Tour_List.as_view(), name="tour_list"),
	url(r'^tour-list/(?P<categoria_slug>[-\w]+)/$',views.Tour_List.as_view(),name = "tour_list_by_categoria"),
	url(r'^tour-detail/(?P<slug>[-\w]+)/$',views.Tour_Detail.as_view(), name = "tour_detail"),
	# url(r'^tour-detail/(?P<id>\d+)/$',views.Tour_Detail.as_view(), name="tour_detail"),
]

home/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

home/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    name =  forms.CharField(max_length=100 , required = False)
    email = forms.EmailField()
    content = forms.CharField(widget=forms.Textarea)

home/views.py
from django.shortcuts import render
from django.views.generic import View
from actividades.models import Actividad
from eventos.models import Evento
from alojamiento.models import Alojamiento
from restaurantes.models import Restaurant
from .forms import ContactForm
from django.core.mail import send_mail 

class Home(View):
    def get(self,request):
        template_name = "home.html"
        form = ContactForm()
        
        context = {
            'form':form,
            
        }
        return render(request, template_name, context)


    def post(self, request):
        template_name = 'home.html'
        form = ContactForm(request.POST)
        if form.is_valid():
            template = 'thanks.html'
            data = form.cleaned_data
            message = 'De {} \n\n Mensaje: {}'.format(data['email'], data['content'])
            send_mail(
                data['subject'],
                message,
                # data['email'],
                'admin@mail.com',
                ['axio.valores@gmail.com'],
                fail_silently = True,
            )
            return render(request, template)
        else:
            form = ContactForm()
        context = {
            'form':form,
        }
        return render(request, template_name, context)


# Create your views here.
class TiendaView(View):
    def get(self,request):
        template_name ="tienda.html"
        return render(request,template_name)

class PrestadoresView(View):
    def get(self,request):
        template_name = 'prestadores.html'
        return render(request,template_name)

class SiteWeb(View):
    def get(self,request):
        template_name = 'site_web.html'
        return render(request,template_name)
        

home/templates/home.html
{%extends 'base.html' %} 
{%load static%}
{%block head%}


{%endblock head%}


    
{%block header%}
        
   <!--Carousel Wrapper-->
        <div id="carousel-example-3" class="carousel slide carousel-fade white-text" data-ride="carousel" data-interval="false">
            <!--Indicators-->
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-3" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-3" data-slide-to="1"></li>
                <li data-target="#carousel-example-3" data-slide-to="2"></li>
            </ol>
            <!--/.Indicators-->

            <!--Slides-->
            <div class="carousel-inner" role="listbox" >

                <!-- First slide -->
                <div class="carousel-item active view hm-black-light" style=" background-image: url({%static 'img/fotico-1.jpg'%});">

                    <!-- Caption -->
                    <div class="full-bg-img flex-center text-center white-text">
                        <ul class="col-lg-6 col-offset-lg-6 col-sm-12">
                            <li>
                                <img src="{% static 'img/teo.png' %}" alt="Teotihuacan mágico" class="img-fluid text-center" width="800" height="800">
                            </li>    
                            <li>
                                <h1 class="sletrero animated slideInLeft h1-responsive title  white-text">¡Teotihuacán a un click!</h1>
                            </li>                            
                        </ul>
                    </div>
                    <!-- /.Caption -->

                </div>
                <!-- /.First slide -->

                <!-- Second slide -->
                <div class="carousel-item view hm-black-light img-fluid" style="background-image: url({%static 'img/Trailer-Park.jpg'%});">

                    <!-- Caption -->
                    <div class="full-bg-img flex-center white-text">
                        <ul class="col-md-12" >
                            <li>
                                <h1 class="sletrero animated slideInLeft h1-responsive title  white-text">Experiencias únicas</h1>
                            </li>
                            <li>
                                <p class="sletrero animated slideInRight flex-item subtitle"></p>
                            </li>
                            
                        </ul>
                    </div> 
                    <!-- /.Caption -->

                </div>
                <!-- /.Second slide -->

                <!-- Third slide -->
                <div class="carousel-item view hm-black-light" style="background-image: url({%static 'img/Header.jpg'%});">
                    <!-- Caption -->
                    <div class="full-bg-img flex-center white-text">
                        <ul class="col-md-12" >
                            <li>
                                <h1 class="sletrero animated slideInLeft h1-responsive title  white-text">Conoce Teotihuacán</h1>
                            </li>
                            <li>
                                <p class="sletrero animated slideInRight flex-item subtitle">más allá de la zona arqueológica</p>
                            </li>
                            
                        </ul>
                    </div> 
                    <!-- /.Caption -->

                </div>
                <!-- /.Third slide -->

            </div>
            <!--/.Slides-->

            <!--Controls-->
            <a class="carousel-control-prev" href="#carousel-example-3" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
			</a>
			<a class="carousel-control-next" href="#carousel-example-3" role="button" data-slide="next">
			    <span class="carousel-control-next-icon" aria-hidden="true"></span>
			    <span class="sr-only">Next</span>
			</a>
            
            <!--/.Controls-->
        </div>
        <!--/.Carousel Wrapper-->

{%endblock header%} 

{% block content%}

<div class="container" style="padding-bottom: 10px;padding-top: 10px;">
    <h1 class="title text-center">Explora Teotihuacán Mágico</h1>
    <hr>
    <div class="row" style="padding-top: 3px;">
        <div class="col-12 col-lg-3 col-md-4 col-sm-6 text-center view overlay hm-orange-strong">
            <div class="card " style="width: 17rem;">
              <a href="{%url 'actividades:actividad_list'%}" >
              <img class="card-img-top" src="../static/img/teo-do.jpg" alt="Teotihuacán Eventos" style="height:150px; weight:50px;">
              <div class="card-block" style="background-color:rgba(255, 152, 0, 0.7);">
                  <h4 class="card-title title-card-white">
                      ¿Qué hacer?
                  </h4>
                  <p class="mask flex-center white-text">Eventos,Actividades..</p>
              </div>
            </div></a>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-6 text-center view overlay hm-blue-strong">
            <div class="card" style="width: 17rem;">
              <a href="{%url 'alojamientos:alojamiento_list'%}" >
              <img class="card-img-top" src="../static/img/Trailer-Park.jpg" alt="Donde Dormir" style="height:150px; weight:50px;">
              <div class="card-block" style="background-color:rgba(0, 150, 136, 0.7);">
                  <h4 class="card-title title-card-white">
                      ¿Dónde Dormir?
                  </h4>
                  <p class="mask flex-center white-text">Hoteles,hostales...</p>
              </div>
            </div> <br> </a>
        </div>
        <div class="col-12 col-lg-3 col-md-4 col-sm-6 text-center view overlay hm-red-strong">
            <div class="card" style="width: 17rem;">
              <a href="{%url 'restaurantes:restaurant_list'%}" >
              <img class="card-img-top" src="../static/img/donde_comer.jpg" alt="Donde Comer" style="height:150px; weight:50px;">
              <div class="card-block" style="background-color:rgba(63, 81, 181, 0.7);">
                  <h4 class="card-title title-card-white">
                      ¿Dónde Comer?
                  </h4>
                  <p class="mask flex-center white-text">Restaurantes, comida tipica,etc..</p>
              </div></a>
            </div>
        </div>
        <div class="col-12 col-lg-3 col-md-4 col-sm-6 text-center view overlay hm-green-strong">
            <div class="card" style="width: 17rem;">
              <a href="{% url 'ruta:lugar_list' %}" >
              <img class="card-img-top" src="../static/img/llegar1.jpg" alt="Teotihuacán Eventos" style="height:150px; weight:50px;">
              <div class="card-block" style="background-color:rgba(205, 220, 57, 0.7);">
                  <h4 class="card-title title-card-white">
                      ¿Cómo llegar?
                  </h4>
                  <p class="mask flex-center white-text">Rutas, transporte, etc...</p>
              </div></a>
            </div>
        </div>
        <div class="col-12 col-lg-3 col-md-4 col-sm-6 text-center view overlay hm-brown-strong">
            <div class="card" style="width: 17rem;">
              <a href="{%url 'tours:tour_list'%}" title="tours teotihuacan_magico">
              <img class="card-img-top" src="../static/img/tours.jpg" alt="Teotihuacán Eventos" style="height:150px; weight:50px;">
              <div class="card-block" style="background-color:rgba(121, 85, 72, 0.7);">
                  <h4 class="card-title title-card-white">
                      Tours
                  </h4>
                  <p class="mask flex-center white-text">Conoce de una manera diferente Teotihuacán..</p>
              </div></a>
            </div>
        </div>
        <div class="col-12 col-lg-3 col-md-4 col-sm-6 text-center view overlay hm-pink-strong">
            <div class="card" style="width: 17rem;">
              <a href="{%url 'shop:list-product'%}" title="artesanias">
              <img class="card-img-top" src="../static/img/art.jpg" alt="Teotihuacán Artesanias" style="height:150px; weight:50px;">
              <div class="card-block" style="background-color:rgba(244, 67, 54, 0.7);">
                  <h4 class="card-title title-card-white">
                      Artesanias
                  </h4>
                  <p class="mask flex-center white-text">Tienda online de artesanias de Teotihuacán..</p>
              </div></a>
            </div>
        </div>
        <div class="col-12 col-lg-3 col-md-4 col-sm-6 text-center view overlay hm-yellow-strong">
            <div class="card" style="width: 17rem;">
              <a href="{%url 'eventos:evento_list'%}" title="eventos-teotihuacán">
              <img class="card-img-top" src="../static/img/eventos.jpg" alt="Teotihuacán Eventos" style="height:150px; weight:50px;">
              <div class="card-block" style="background-color:rgba(255, 235, 59, 0.7);">
                  <h4 class="card-title title-card-white">
                      Eventos
                  </h4>
                  <p class="mask flex-center white-text">Calendario de eventos en Teotihuacán..</p>
              </div></a>
            </div>
        </div>
        <div class="col-12 col-lg-3 col-md-4 col-sm-6 text-center view overlay hm-teal-strong">
            <div class="card" style="width: 17rem;">
              <a href="{%url 'servicios:servicio_list'%}" title="servicios_basicos">
              <img class="card-img-top" src="../static/img/basics.png" alt="Teotihuacán Básicos" style="height:150px; weight:50px;">
              <div class="card-block" style="background-color:rgba(76, 175, 80, 0.7);">
                  <h4 class="card-title title-card-white">
                      Básicos
                  </h4>
                  <p class="mask flex-center white-text">Números de emergencia,gasolina,etc...</p>
              </div></a>
            </div>
        </div>
    </div>
</div>
{%include "blog/publicaciones_comentadas.html" %}


{%endblock content%}

{%block scripts%}
 
{%endblock scripts%} 

home/templates/prestadores.html
{%extends 'base.html' %} 

{%load static%}

{%block head%}
	
{%endblock head%}

{%block header%}
<!-- streak -->
<div class="streak hm-black-strong streak-lg streak-photo view " style="background-image:url({%static 'img/teo.png'%})">
		<div class="flex-center mask">
			<ul class="white-text smooth-scroll title">
				<li><h2 class="h2-responsive"> Prestadores de Servicios</h2></li>
			</ul>
		</div>
</div>

{%endblock header%}



{% block content%}

<section class="services">
	<div class="container">
		<h1 class="title text-center">Estimado Prestador de Servicios:</h1>
		<p class="text-center">En Teotihuacán Mágico estamos convencidos en tener alianzas que nos permitan crecer exponencialmente. Es por ello que te mostramos todos los servicios que puedes adquirir con Teotihuacán Mágico.</p>
		<hr>


	</div>

	<div class="container" style="padding-bottom: 10px;padding-top: 10px;">
    <div class="row" style="padding-top: 3px;">
        <div class="col-12 col-lg-3 col-md-4 col-sm-6 text-center view overlay hm-orange-strong">
            <div class="card " style="width: 17rem;">
              <a href="{%url 'home:siteweb'%}" >
              <img class="card-img-top" src="../static/img/site_web.jpg" alt="Teotihuacán Eventos" style="height:150px; weight:50px;">
              <div class="card-block" style="background-color:rgba(255, 152, 0, 0.7);">
                  <h4 class="card-title title-card-white">
                      Sitios Web
                  </h4>
                  <p class="mask flex-center white-text">Dinámicos y estáticos</p>
              </div>
            </div></a>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-6 text-center view overlay hm-blue-strong">
            <div class="card" style="width: 17rem;">
              <a href="{%url 'alojamientos:alojamiento_list'%}" >
              <img class="card-img-top" src="../static/img/marketing.jpg" alt="Donde Dormir" style="height:150px; weight:50px;">
              <div class="card-block" style="background-color:rgba(0, 150, 136, 0.7);">
                  <h4 class="card-title title-card-white">
                      Marketing Digital
                  </h4>
                  <p class="mask flex-center white-text">Promocionales, redes sociales...</p>
              </div>
            </div> <br> </a>
        </div>
        <div class="col-12 col-lg-3 col-md-4 col-sm-6 text-center view overlay hm-red-strong">
            <div class="card" style="width: 17rem;">
              <a href="{%url 'restaurantes:restaurant_list'%}" >
              <img class="card-img-top" src="../static/img/imagen.jpg" alt="Donde Comer" style="height:150px; weight:50px;">
              <div class="card-block" style="background-color:rgba(63, 81, 181, 0.7);">
                  <h4 class="card-title title-card-white">
                      Diseño Imagen
                  </h4>
                  <p class="mask flex-center white-text">Logotipos. tarjetas ,hojas...</p>
              </div></a>
            </div>
        </div>
        <div class="col-12 col-lg-3 col-md-4 col-sm-6 text-center view overlay hm-green-strong">
            <div class="card" style="width: 17rem;">
              <a href="{% url 'ruta:lugar_list' %}" >
              <img class="card-img-top" src="../static/img/content.jpg" alt="Teotihuacán Eventos" style="height:150px; weight:50px;">
              <div class="card-block" style="background-color:rgba(205, 220, 57, 0.7);">
                  <h4 class="card-title title-card-white">
                      Contenido
                  </h4>
                  <p class="mask flex-center white-text">Infografias, Articulos, etc...</p>
              </div></a>
            </div>
        </div>
    </div>
</div>
	
</section>

{%endblock content%}



{%block scripts%}

{%endblock scripts%}

home/templates/site_web.html
{% extends 'base_detail.html'%}
{% load static%}

{% block content %}


<section class="blog_d view" style="background-image: url({%static 'img/site_web.jpg'%}); padding-top:100px;">
    <div class="container text-center" style="padding: 70px;">
      <div class="col-lg-6 offset-lg-3">
        <h2 class="title_site_web">Sitios Web</h2>
        <p class="subtitle_site_web">Dinamicos y estaticos</a>.</p>
        <p class="subtitle_site_web"></p>
      </div>
    </div>
</section>	

<section>
    <div class="container" style="padding-top:20px;">
      <div class="row">
        <div class="col-lg-8 text-justify">
          <p>Pre-refrigerator woman face forwards construct jeans rebar corrupted monofilament cardboard. Smart-claymore mine free-market network sunglasses ablative physical savant courier uplink spook DIY crypto-8-bit. Uplink claymore mine courier tower face forwards pen footage systemic post-refrigerator range-rover franchise. Dome nano-tanto math-corrupted Legba camera systemic Shibuya media wonton soup. Shanty town beef noodles sprawl courier pistol voodoo god dolphin systema tanto construct warehouse apophenia office weathered cyber-kanji. Sign plastic papier-mache pen modem chrome otaku drone tank-traps 3D-printed DIY shrine spook bicycle assault woman rebar. Receding grenade dissident sprawl modem claymore mine human digital sunglasses 8-bit. </p>
        </div> 
        <div class="col-lg-4 col-sm-12">
          <h1>Aqui no se que poner xD</h1>
        </div>
      </div>
    </div>
</section>

{% endblock content %}

home/templates/thanks.html
{%extends 'base.html' %} 

{%load static%}

{%block head%}

{%endblock head%}

{%block header%}
<!-- streak -->
<div class="streak hm-black-strong streak-lg streak-photo view" style="background-image:url({%static 'img/pic02.jpg'%})">
		<div class="flex-center mask">
			<ul class="white-text smooth-scroll title">
				<li><h2 class="h2-responsive"> Gracias por tu visita</h2></li>
			</ul>
		</div>
</div>
{%endblock header%}


{% block content%}

{%endblock content%}



{%block scripts%}

{%endblock scripts%}

home/templates/tienda.html
{%extends 'base.html' %} 

{%load static%}

{%block head%}

{%endblock head%}

{%block header%}
<!-- streak -->
<div class="streak hm-black-strong streak-lg streak-photo view" style="background-image:url({%static 'img/art.jpg'%})">
		<div class="flex-center mask">
			<ul class="white-text smooth-scroll title">
				<li><h2 class="h2-responsive"> Tienda de Artesanias</h2></li>
				<li><p class="subtitle">Proximamente....</p></li>
			</ul>
		</div>
</div>
{%endblock header%}


{% block content%}

{%endblock content%}



{%block scripts%}

{%endblock scripts%}