TeotiShopy/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from home import urls as UrlsHome
from actividades import urls as UrlsActividades
from eventos import urls as UrlsEventos
from alojamiento import urls as UrlsAlojamientos
from blog import urls as UrlsBlog
from restaurantes import urls as UrlsRestaurantes
from servicios import urls as UrlsServicios
from tour import urls as UrlsTour
from shop import urls as UrlsShop
from ruta import urls as UrlsRuta

from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include(UrlsBlog,namespace="blog")),
    url(r'^',include(UrlsHome,namespace="home")),
    url(r'^',include(UrlsEventos,namespace="eventos")),
    url(r'^',include(UrlsActividades,namespace="actividades")),
    url(r'^',include(UrlsAlojamientos,namespace="alojamientos")), 
    url(r'^',include(UrlsRestaurantes,namespace="restaurantes")),
    url(r'^',include(UrlsServicios,namespace="servicios")),
    url(r'^',include(UrlsTour,namespace="tours")),
    url(r'^',include(UrlsShop,namespace="shop")),
    url(r'^',include(UrlsRuta,namespace="ruta")),        
    url(
    	regex=r'^media/(?P<path>.*)$',
    	view=serve,
    	kwargs = {'document_root':settings.MEDIA_ROOT}),
]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.PostList.as_view(), name='post_list'),
	url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.PostList.as_view(), name="post_list_by_tag"),
	url(r'^list/$', views.PostListView.as_view(), name='post_list_view'),
	url(r'^(?P<post>[-\w]+)/$', views.PostDetailView.as_view(), name="post_detail"),
	url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.PostDetail.as_view(), name="post_detail"),
	url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/(?P<ready>\d+)/$', views.PostDetail.as_view(), name="post_detail_ready"),
	url(r'^(?P<post_id>\d+)/share/$', views.SentEmailView.as_view(), name="post_share"),
	url(r'^(?P<post_id>\d+)/(?P<conf>\d+)/share/$', views.SentEmailView.as_view(), name="post_share_conf"),
]

servicios/urls.py
from django.conf.urls import url
from . import views

urlpatterns =[
	url(r'^servicios-list/$',views.Servicio_List.as_view(), name="servicio_list"),
	url(r'^servicios-list/(?P<categoria_slug>[-\w]+)/$',views.Servicio_List.as_view(), name="servicio_list_by_categoria"),
    url(r'^servicio-detail/(?P<slug>[-\w]+)/$',views.Servicio_Detail.as_view(), name="servicio_detail"),
	# url(r'^servicio-detail/(?P<id>\d+)/$',views.Servicio_Detail.as_view(), name="servicio_detail"),
]

servicios/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse

class CategoriaServicio(models.Model):
    nombre = models.CharField(max_length=250, db_index=True)
    slug = models.SlugField(max_length = 250, db_index=True, unique=True)

    class Meta():
        ordering = ('nombre',)
        verbose_name='categoria_servicio'
        verbose_name_plural = 'categorias_servicio'

    def __str__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse ('servicios:servicio_list_by_categoria', args=[self.slug])


# Create your models here.
class Servicio(models.Model):
    categoria = models.ForeignKey(CategoriaServicio, related_name='categoria')
    nombre = models.CharField(max_length=100, blank=True, null=True)
    slug = models.SlugField(max_length=100)
    descripcion = models.TextField()
    logo = models.ImageField(upload_to='logo-servicio',default='img/teo2.png', blank=True,null=True)
    portada = models.ImageField(upload_to='portada-servicio',default='img/teo2.png', blank=True,null=True)
    ubicacion = models.CharField(max_length=300)
    telefono = models.CharField(max_length=15)
    telefono2 = models.CharField(max_length=150,blank=True,null=True)
    correo = models.EmailField(max_length=100, blank=True,null=True,default='contacto@teotihuacanmagico.com.mx')
    facebook = models.URLField(max_length=200, blank=True,null=True,default='https://www.facebook.com/teotihuacanmagicomx/')
    twitter =models.URLField(max_length=200, blank=True,null=True,default='https://www.facebook.com/teotihuacanmagicomx/')
    instagram = models.URLField(max_length=200, blank=True,null=True,default='https://www.facebook.com/teotihuacanmagicomx/')
    youtube = models.URLField(max_length=200, blank=True,null=True,default='https://www.facebook.com/teotihuacanmagicomx/')
    caracteristicas = models.TextField(max_length=300)
    horario = models.CharField(max_length=300, blank=True,null=True)
    image = models.ImageField(upload_to='portadas', default='img/teo2.png', null=True, blank=True)
    imagedos = models.ImageField(upload_to='portadas', default='img/teo2.png', null=True, blank=True)
    imagetres = models.ImageField(upload_to='portadas', default='img/teo2.png', null=True, blank=True)
    lat = models.FloatField(null=True, blank=True, default=None)
    lng = models.FloatField(null=True, blank=True, default=None)
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre
    
    def get_absolute_url(self):
        return reverse('servicios:servicio_detail', args=[self.slug])

class Marcador(models.Model):
    servicio = models.ForeignKey(Servicio, related_name='servicio')
    nombre = models.CharField(max_length=250, blank=True, null=True)
    latitud = models.FloatField(null=True, blank=True, default=None)
    longitud= models.FloatField(null=True, blank=True, default=None)

    def __str__(self):
        return self.nombre

servicios/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from .models import Servicio,CategoriaServicio,Marcador

class Servicio_List(View):
	def get(self,request,categoria_slug = None):
		template_name = "servicio_list.html"
		categoria = None
		categorias = CategoriaServicio.objects.all()
		servicios = Servicio.objects.filter(available = True)
		if categoria_slug:
			categoria = get_object_or_404(CategoriaServicio,slug = categoria_slug)
			servicios = servicios.filter(categoria=categoria)
		context = {
			'categoria': categoria,
			'categorias': categorias,
			'servicios':servicios,
		}
		return render(request,template_name,context)

class Servicio_Detail(View):
	def get(self, request,slug):
		template_name = "servicio_detail.html"
		servicio = get_object_or_404(Servicio, slug = slug)
		marcadores = Marcador.objects.all().filter(servicio = servicio)
		context={
			'marcadores': marcadores,
			'servicio':servicio,
		}
		print(marcadores)
		return render(request,template_name,context)

servicios/templates/servicio_detail.html
{%extends 'base_detail.html' %}
{% load actividad_tags %}
{%load jsonify %}
{%load static%}

{%block head%}
{%endblock head%}

{% block content%}


<div class="container" style="padding-top:150px;margin-bottom: 0px; background-color: #fafafa">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-8 text-center">
            <img src="{{servicio.logo.url}}" class="img-fluid" width="250" height="250">
        </div>
        <div class="col-lg-12 col-md-12 col-sm-8 text-center">
            <h2 class="title text-center">{{servicio.nombre}}</h2>
            <p class="subtitle title">Categoria: {{servicio.categoria.nombre}}</p>
            <p class="subtitle title text-center">Horario: {{servicio.horario}}</p>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-12">
            <h2 class="subtitle title text-center">Contácto</h2>
            <p><i class="fa fa-map-marker" aria-hidden="true"></i> {{servicio.ubicacion}}</p>
            <p><i class="fa fa-phone" aria-hidden="true"></i> {{servicio.telefono}}</p>
            <p><i class="fa fa-mobile" aria-hidden="true"></i> {{servicio.telefono2}}</p>
            <hr>
            <div class="container text-center">
                <h2 class="subtitle title text-center">Redes Sociales</h2>
                    <div class="row">
                            <div class="col-lg-3 col-sm-3">
                                <p><a href="{{servicio.facebook}}" style="color:blue;" target="_blank"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></p>
                            </div>
                            <div class="col-lg-3 col-sm-3">
                                <p><a href="{{servicio.twitter}}" style="color:cornflowerblue;" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a></p>
                            </div>
                            <div class="col-lg-3 col-sm-3">
                                <p><a href="{{servicio.instagram}}" style="color: rgba-purple-strong;" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a></p>
                            </div>
                            <div class="col-lg-3 col-sm-3">
                                <p><a href="{{servicio.youtube}}" style="color:red;" target="_blank"><i class="fa fa-youtube" aria-hidden="true"></i></a></p>
                            </div>  
                    </div>
            </div>
            <hr>
            <h2 class="subtitle title text-center">Mapa</h2>
            <div id='map' style='width:auto; height: 300px;'></div>
            <hr>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12">
            <h2 class="subtitle title text-center">Caracteristicas</h2>
            <p>{{servicio.caracteristicas|markdown}}</p>
            <hr>
            <h2 class="subtitle title text-center"><i class="fa fa-camera" aria-hidden="true"></i> Fotografías</h2>
            <div class="container" style="padding-top:5px;padding-bottom:10px;">
            <!--First row-->
                <div class="row mb-2 mt-1">
                    
                    <!--Carousel header-->
                    <div class="col-lg-12 col-md-12 col-sm-12"> 

                        <!--Carousel Wrapper-->
                        <div id="carousel-example-1" class="carousel slide carousel-fade z-depth-1-half" data-ride="carousel">
                            <!--Indicators-->
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-1" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-1" data-slide-to="1"></li>
                                <li data-target="#carousel-example-1" data-slide-to="2"></li>
                            </ol>
                            <!--/.Indicators-->

                            <!--Slides-->
                            <div class="carousel-inner" role="listbox">
                                <!--First slide-->
                                <div class="carousel-item active">
                                    <a href="#!"><img src="{{servicio.image.url}}" alt="First slide" class="img-fluid"></a>
                                </div>
                                <!--/First slide-->

                                <!--Second slide-->
                                <div class="carousel-item">
                                    <a href="#!"><img src="{{servicio.imagedos.url}}" alt="Second slide" class="img-fluid"></a>
                                </div>
                                <!--/Second slide-->

                                <!--Third slide-->
                                <div class="carousel-item">
                                    <a href="#!"><img src="{{servicio.imagetres.url}}" alt="Third slide" class="img-fluid"></a>
                                </div>
                                <!--/Third slide-->
                            </div>
                            <!--/.Slides-->

                            <!--Controls-->
                            <a class="carousel-control-prev" href="#carousel-example-1" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carousel-example-1" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                            <!--/.Controls-->
                        </div>
                        <!--/.Carousel Wrapper-->

                    </div>
                    <!--/Carousel header-->
                    
                </div>
                <!--/First row-->
            </div>
        </div>
    </div>
</div>


<script>

      function initMap() {
        var myLatLng = {lat: {{servicio.lat|jsonify}} , lng: {{servicio.lng|jsonify}} };

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 14,
          center: myLatLng
        });
        {% for m  in marcadores  %}
          var marker = new google.maps.Marker({
          position:{lat: {{m.latitud|jsonify}} , lng: {{m.longitud|jsonify}} },
          map: map,
          title: '{{m.nombre|jsonify}}'
        });  
        {% endfor %}
        
      }

</script>
<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDtjM5A6W-i81IPpnYzXbwDpRbNJ0iVc0E&callback=initMap">
</script>


{%endblock content%}


{%block scripts%}
 
{%endblock scripts%}

servicios/templates/servicio_list.html
{%extends 'base.html'%}
{%load static%}
{% load actividad_tags %}
{%block head%}

{%endblock head%}

{%block header%}
<!-- streak -->
<div class="streak hm-black-strong streak-lg streak-photo view" style="background-image:url({%static 'img/bg-3.jpg'%})">
		<div class="flex-center mask">
			<ul class="white-text smooth-scroll title">
				<li><h2 class="h2-responsive"> Servicios</h2></li>
				<li><h5 class="text-center  wow fadeIn" data-wow-delay="0.2s">Desde médicos hasta fotógrafos...</h5></li>

			</ul>
		</div>
</div>
<!-- /.streak -->
{%endblock header%}
{%block content%}
<div class="container text-center">
	<div class="row">
		<div class="col-12 col-sm-12 col-md-12 col-lg-12">	
			<h2 class="title">Categorías</h2>
			<ul class="list-categoria">
				<li {% if not categoria  %}{% endif %} id="catego">
					<a href="{%url 'servicios:servicio_list' %}" class="list">Todas</a>
				</li>
				{% for c in categorias %}
				<li{% if categoria.slug == c.slug %}{% endif %} id="catego">
					<a href="{{c.get_absolute_url}}" class="list">{{c.nombre}}</a>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
</div>

<div class="container" style="padding-bottom: 30px;padding-top: 10px;">
	<h2 class="text-center title">
		{% if categoria %}
			{{categoria.nombre}}
		{%else%}
			Todos
		{% endif %}
	</h2>
	<hr>
	<div class="row">
		{%for Servicio in servicios%}
		<div class="col-lg-3 col-md-4 col-sm-6 text-center">
			<div class="card bordesito" style="width: 16rem;">
			  <img class="card-img-top" src="{{Servicio.logo.url}}" alt="Teotihuacan Mágico" width="250" height="250">
			  <div class="card-block">
			    <h4 class="card-title title-card text-center">{{Servicio.nombre}}</h4>
			    <!--<p class="card-text">{{Servicio.description|truncatewords_html:20}}</p>-->
			    <p class="card-text">{{Servicio.categoria}}</p>
				<p class="card-text"><i class="fa fa-map-marker" aria-hidden="true"></i> {{Servicio.ubicacion}}</p>
			    <a href="{{Servicio.get_absolute_url}}" class="btn btn-primary">más información...</a>
			  </div>
			</div>
		</div>
		{%endfor%}
	</div>
</div>

{%endblock content%}