TeotiShopy/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from home import urls as UrlsHome
from actividades import urls as UrlsActividades
from eventos import urls as UrlsEventos
from alojamiento import urls as UrlsAlojamientos
from blog import urls as UrlsBlog
from restaurantes import urls as UrlsRestaurantes
from servicios import urls as UrlsServicios
from tour import urls as UrlsTour
from shop import urls as UrlsShop
from ruta import urls as UrlsRuta

from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include(UrlsBlog,namespace="blog")),
    url(r'^',include(UrlsHome,namespace="home")),
    url(r'^',include(UrlsEventos,namespace="eventos")),
    url(r'^',include(UrlsActividades,namespace="actividades")),
    url(r'^',include(UrlsAlojamientos,namespace="alojamientos")), 
    url(r'^',include(UrlsRestaurantes,namespace="restaurantes")),
    url(r'^',include(UrlsServicios,namespace="servicios")),
    url(r'^',include(UrlsTour,namespace="tours")),
    url(r'^',include(UrlsShop,namespace="shop")),
    url(r'^',include(UrlsRuta,namespace="ruta")),        
    url(
    	regex=r'^media/(?P<path>.*)$',
    	view=serve,
    	kwargs = {'document_root':settings.MEDIA_ROOT}),
]

actividades/urls.py
from django.conf.urls import url
from . import views

urlpatterns =[
	url(r'^actividad-list/$',views.Activity_List.as_view(), name="actividad_list"),
	url(r'^actividad-list/(?P<categoria_slug>[-\w]+)/$',views.Activity_List.as_view(),name="actividad_list_by_categoria"),
	url(r'^actividad-detail/(?P<slug>[-\w]+)/$',views.Activity_Detail.as_view(), name="actividad_detail"),
	# url(r'^actividad-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$',views.Activity_Detail.as_view(), name="actividad_detail"),
]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.PostList.as_view(), name='post_list'),
	url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.PostList.as_view(), name="post_list_by_tag"),
	url(r'^list/$', views.PostListView.as_view(), name='post_list_view'),
	url(r'^(?P<post>[-\w]+)/$', views.PostDetailView.as_view(), name="post_detail"),
	url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.PostDetail.as_view(), name="post_detail"),
	url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/(?P<ready>\d+)/$', views.PostDetail.as_view(), name="post_detail_ready"),
	url(r'^(?P<post_id>\d+)/share/$', views.SentEmailView.as_view(), name="post_share"),
	url(r'^(?P<post_id>\d+)/(?P<conf>\d+)/share/$', views.SentEmailView.as_view(), name="post_share_conf"),
]

actividades/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse
from datetime import datetime
import os

def get_image_path(instance, filename):
    return os.path.join('photos', str(instance.id), filename)
# Create your models here.
class Categoria(models.Model):
	nombre = models.CharField(max_length=250, db_index=True)
	slug = models.CharField(max_length=250, db_index=True, unique=True)

	class Meta():
		ordering = ('nombre',)
		verbose_name='categoria'
		verbose_name_plural='categorias'

	def __str__(self):
		return self.nombre

	def get_absolute_url(self):
		return reverse ('actividades:actividad_list_by_categoria', args=[self.slug])

class Actividad(models.Model):
	categoria = models.ForeignKey(Categoria,related_name='actividades')
	nombre = models.CharField(max_length=200,db_index=True)
	slug = models.SlugField(max_length=200,db_index=True)
	logo = models.ImageField(upload_to='logo-actividades', blank=True, null=True)
	portada1 = models.ImageField(upload_to=get_image_path, blank=True,null=True)
	portada2 = models.ImageField(upload_to=get_image_path, blank=True,null=True)
	portada3 = models.ImageField(upload_to=get_image_path, blank=True,null=True)
	fecha_inicial = models.DateTimeField( blank=True, null=True)
	fecha_final = models.DateTimeField(blank=True,null=True)
	fecha_unica = models.DateTimeField( blank=True,null=True)
	horario = models.CharField(max_length=40,blank=True,null=True)
	descripcion = models.TextField()
	ubicacion = models.CharField(max_length=200)
	sugerencia = models.TextField(blank=True,null=True)
	telefono = models.CharField(max_length=150,blank=True,null=True)
	telefono2 = models.CharField(max_length=150,blank=True,null=True)
	correo = models.EmailField(max_length=100, blank=True,null=True,default='contacto@teotihuacanmagico.com.mx')
	facebook = models.URLField(max_length=200, blank=True,null=True,default='https://www.facebook.com/teotihuacanmagicomx/')
	twitter =models.URLField(max_length=200, blank=True,null=True,default='https://www.facebook.com/teotihuacanmagicomx/')
	instagram = models.URLField(max_length=200, blank=True,null=True,default='https://www.facebook.com/teotihuacanmagicomx/')
	youtube = models.URLField(max_length=200, blank=True,null=True,default='https://www.facebook.com/teotihuacanmagicomx/')
	sitio_web = models.URLField(max_length=500,blank=True,null=True,default='http://www.teotihuacanmagico.com.mx')
	available= models.BooleanField(default=True)
	lat = models.FloatField(null=True, blank=True, default=None)
	lng = models.FloatField(null=True, blank=True, default=None)

	def __str__(self):
		return (self.nombre)

	def get_absolute_url(self):
		return reverse('actividades:actividad_detail',args=[self.slug])

class Precio(models.Model):
	tipo = models.CharField(max_length=140,blank=True, null=True)
	costo = models.DecimalField(max_digits=10,decimal_places=2)
	incluye = models.TextField(null=True,blank=True)
	no_incluye = models.TextField(null=True,blank=True)
	actividad = models.ForeignKey(Actividad,related_name='actividades', on_delete=models.CASCADE)

	def __str__(self):
		return (self.actividad.nombre)

class Marcador(models.Model):
    actividad = models.ForeignKey(Actividad, related_name='actividad')
    nombre = models.CharField(max_length=250, blank=True, null=True)
    latitud = models.FloatField(null=True,blank=True, default=None)
    longitud = models.FloatField(null=True,blank=True,default=None)

    def __str__(self):
        return self.nombre
# class Horario(models.Model):
# 	actividadh = models.ForeignKey(Actividad,related_name='actividadh',on_delete=models.CASCADE)
# 	nombre = models.CharField(max_length=250,blank=True,null=True)
# 	horas = models.CharField(max_length=50,blank=True,null=True)

# 	def __str__(self):
# 		return (self.actividadh.nombre)

actividades/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from .models import Actividad, Categoria, Precio, Marcador


class Activity_List(View):

    def get(self, request, categoria_slug=None):
        template_name = "actividad_list.html"
        categoria = None
        categorias = Categoria.objects.all()
        actividades = Actividad.objects.filter(available=True)
        if categoria_slug:
            categoria = get_object_or_404(Categoria, slug=categoria_slug)
            actividades = actividades.filter(categoria=categoria)
        context = {
            'categoria': categoria,
            'categorias': categorias,
            'actividades': actividades,
        }
        return render(request, template_name, context)


class Activity_Detail(View):

    def get(self, request, slug):
        template_name = "actividad_detail.html"
        actividad = get_object_or_404(Actividad, slug=slug)
        precios = Precio.objects.all().filter(actividad=actividad)
        marcadores = Marcador.objects.all().filter(actividad=actividad)
        # horarios = Horario.objects.all().filter(actividadh=actividad)
        context = {
            'actividad': actividad,
            'precios': precios,
            'marcadores':marcadores,
            # 'horarios': horarios,
        }
        return render(request, template_name, context)
# Create your views here.

actividades/templates/actividad_detail.html
{%extends 'base_detail.html' %} 
{% load actividad_tags %}
{% load jsonify %}
{%load static%}
{%block head%}
{%endblock head%}

{% block content%}

<div class="container" style="padding-top:150px;margin-bottom: 0px; background-color: #fafafa">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-8 text-center">
            <img src="{{actividad.logo.url}}" class="img-circle" style="width: 250px; height: 250px;">
            <hr>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-8">
            
            <h2 class="title text-center">{{actividad.nombre}}</h2>
            <p class="subtitle title text-center">Categoria: {{actividad.categoria.nombre}}</p>

            {% if actividad.available %}
            <p class=" subtitle title text-center">Status: Activa</p>    
            {% else %}
            <p class="subtitle title text-center">Status: No disponible</p>
            {%endif%}

            {%if actividad.fecha_inicial and actividad.fecha_final %}
            <p class="subtitle text-center">Del: {{actividad.fecha_inicial|date:"D d M Y"}}  Al: {{actividad.fecha_final|date:"D d M Y"}}</p>   
            {%elif actividad.fecha_unica %}
            <p class = "subtitle title text-center">Fecha: {{actividad.fecha_unica|date:"D d M Y P"}}</p>
            {% else %}
            <p class="text-center subtitle title">Sin Fechas especificas</p>
            {%endif%}
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-12">
            <p class="subtitle text-center title"><i class="fa fa-bolt" aria-hidden="true"></i> Información General</p>
            <!--<p><i class="fa fa-calendar" aria-hidden="true"></i> {{evento.fecha}}h.</p>-->
            <p><i class="fa fa-map-marker" aria-hidden="true"></i> {{actividad.ubicacion}}.</p>

            {%if actividad.telefono%}
            <p><i class="fa fa-phone" aria-hidden="true"></i> {{actividad.telefono}}</p>
            {%else%}
            <p><i class="fa fa-phone" aria-hidden="true"></i> No Disponible</p>
            {%endif%}

            {%if actividad.telefono2%}
            <p><i class="fa fa-mobile" aria-hidden="true"></i> {{actividad.telefono2}}</p>
            {%else%}
            <p><i class="fa fa-mobile" aria-hidden="true"></i> No Disponible</p>
            {%endif%}

            <p><i class="fa fa-envelope" aria-hidden="true"></i> {{actividad.correo}}</p>
            <!--<p><a href="{{actividad.sitio_web}}" target="_blank" style="color:#000;"><i class="fa fa-globe" aria-hidden="true"></i> {{actividad.sitio_web}}</a></p>-->
            <hr>
            <div class="container text-center">
                <p class="subtitle title text-center"> Redes Sociales</p>
                <div class="row">
                    <div class="col-lg-3 col-sm-3">
                        <p><a href="{{actividad.facebook}}" style="color:blue;" target="_blank"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></p>
                    </div>
                    <div class="col-lg-3 col-sm-3">
                        <p><a href="{{actividad.twitter}}" style="color:cornflowerblue;" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a></p>
                    </div>
                    <div class="col-lg-3 col-sm-3">
                        <p><a href="{{actividad.instagram}}" style="color: rgba-purple-strong;" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a></p>
                    </div>
                    <div class="col-lg-3 col-sm-3">
                        <p><a href="{{actividad.youtube}}" style="color:red;" target="_blank"><i class="fa fa-youtube" aria-hidden="true"></i></a></p>
                    </div>  
                </div>
            </div>
            <hr>
             <h3 class="subtitle title text-center"><i class="fa fa-money" aria-hidden="true"></i> Precios</h3>
            {%for actividad in precios%}
            <p class="subtitle title"><span class="subtitle title">{{actividad.tipo}}</span> = ${{actividad.costo}} MXN.</p>
            <p>{{actividad.incluye|markdown}}</p>
            <p>{{actividad.no_incluye|markdown}}</p>
            {%endfor%}
            <hr>
            <h2 class="subtitle title text-center"><i class="fa fa-map" aria-hidden="true"></i> Mapa</h2>
            <div id='map' style='width:auto; height: 300px;'></div>
            <hr>  
            <!-- <p>Servicios Extras: {%for evento in servicios_extra%}{{evento.tipo}},{%endfor%}</p> -->
            <!-- <hr>
            <h3 class="subtitle">Servicios</h3>
            <div class="container text-center">
                    <div class="row">
                            <div class="col-lg-3 col-sm-3">
                                {%if evento.banos == True %}
                                <p><i class="fa fa-bath" aria-hidden="true"></i><br>Baños</p>
                                {%else%}
                                <p></p>
                                {%endif%}
                            </div>
                            <div class="col-lg-3 col-sm-3">
                                {%if evento.estacionamiento == True %}
                                <p><i class="fa fa-car" aria-hidden="true"></i><br>Estacionamiento</p>
                                {%else%}
                                <p><i class="fa fa-car" aria-hidden="true"></i><br>No Disponible</p>
                                {%endif%}
                            </div> 
                    </div>
            </div> -->
        </div>
            
        <div class="col-lg-6 col-md-6 col-sm-12">
            <p class="subtitle title text-center"><i class="fa fa-eye" aria-hidden="true"></i> Descripción: <br> {{actividad.descripcion|markdown}}</p>            
            <hr>
            <p class="subtitle title text-center"><i class="fa fa-bell" aria-hidden="true"></i> Sugerencias: <br>{{actividad.sugerencia|markdown}}</p>
            <hr>
            <p class="subtitle title text-center"><i class="fa fa-camera" aria-hidden="true"></i> Fotografias</p>
            <div class="container" style="padding-top:0px;">
            <!--First row-->
                        <div class="row mb-2 mt-1">
                            
                            <!--Carousel header-->
                            <div class="col-lg-12 col-md-12 col-sm-12"> 

                                <!--Carousel Wrapper-->
                                <div id="teotihuacan-magico-1" class="carousel slide carousel-fade z-depth-1-half" data-ride="carousel">
                                    <!--Indicators-->
                                    <ol class="carousel-indicators">
                                        <li data-target="#teotihuacan-magico-1" data-slide-to="0" class="active"></li>
                                        <li data-target="#teotihuacan-magico-1" data-slide-to="1"></li>
                                        <li data-target="#teotihuacan-magico-1" data-slide-to="2"></li>
                                    </ol>
                                    <!--/.Indicators-->

                                    <!--Slides-->
                                    <div class="carousel-inner" role="listbox">
                                        <!--First slide-->
                                        <div class="carousel-item active">
                                            <a href="#!"><img src="{{actividad.portada1.url}}" alt="First slide" class="img-fluid"></a>
                                        </div>
                                        <!--/First slide-->

                                        <!--Second slide-->
                                        <div class="carousel-item">
                                            <a href="#!"><img src="{{actividad.portada2.url}}" alt="Second slide" class="img-fluid"></a>
                                        </div>
                                        <!--/Second slide-->

                                        <!--Third slide-->
                                        <div class="carousel-item">
                                            <a href="#!"><img src="{{actividad.portada3.url}}" alt="Third slide" class="img-fluid"></a>
                                        </div>
                                        <!--/Third slide-->
                                    </div>
                                    <!--/.Slides-->

                                    <!--Controls-->
                                    <a class="carousel-control-prev" href="#teotihuacan-magico-1" role="button" data-slide="prev">
                                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                    <a class="carousel-control-next" href="#teotihuacan-magico-1" role="button" data-slide="next">
                                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                        <span class="sr-only">Next</span>
                                    </a>
                                    <!--/.Controls-->
                                </div>
                                <!--/.Carousel Wrapper-->

                            </div>
                            <!--/Carousel header-->
                            
                        </div>
                        <!--/First row-->
            </div>
            <div class="col-lg-12 col-md-12 col-sm-8 text-center">
                <a href="{{actividad.url_boletos}}" class="btn btn-danger" target="_blank">+ Información</a>
            </div>     
        </div>
    </div>
</div>
<script>

      function initMap() {
        var myLatLng = {lat: {{actividad.lat|jsonify}} , lng: {{actividad.lng|jsonify}} };

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 14,
          center: myLatLng
        });
        {% for m  in marcadores  %}
          var marker = new google.maps.Marker({
          position:{lat: {{m.latitud|jsonify}} , lng: {{m.longitud|jsonify}} },
          map: map,
          title: '{{m.nombre|jsonify}}'
        });  
        {% endfor %}
        
      }

</script>
<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDtjM5A6W-i81IPpnYzXbwDpRbNJ0iVc0E&callback=initMap">
</script>
{%endblock content%}


{%block scripts%}

{%endblock scripts%}

actividades/templates/actividad_list.html
{%extends 'base.html' %}
{% load actividad_tags %}
{%load static%}
{%block head%}

{%endblock head%}

{%block header%}

<!-- streak -->
<div class="streak hm-black-strong streak-lg streak-photo view" style="background-image:url({%static 'img/Header.jpg'%})">
	<div class="flex-center mask">
		<ul class="white-text smooth-scroll title">
			<li><h2 class="h2-responsive">¿Qué hacer?</h2></li>
			<li><h5 class="text-center  wow fadeIn subtitle" data-wow-delay="0.2s">Conoce actividades,festividades y más... </h5></li>
		</ul>
	</div>
</div>
<!-- /.streak -->
{%endblock header%}
{%block content%}
<div class="container text-center">
	<div class="row">
		<div class="col-12 col-sm-12 col-md-12 col-lg-12">	
			<h2 class="title">Categorias</h2>
			<ul class="list-categoria">
				<li {% if not categoria  %}{% endif %} id="catego">
					<a href="{%url 'actividades:actividad_list' %}" class="list">Todas</a>
				</li>
				{% for c in categorias %}
				<li{% if categoria.slug == c.slug %}{% endif %} id="catego">
					<a href="{{c.get_absolute_url}}" class="list">{{c.slug}}</a>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
</div>
<div class="container" style="padding-bottom: 10px;padding-top: 10px;">
		<h2 class="text-center title">
			{% if categoria %}
				{{categoria.nombre}}
			{%else%}
				Todas
			{% endif %}
		</h2>
		{%for Actividad in actividades%}
		{% if forloop.first %}
		<div class="row" style="padding-top: 3px;">
		{%endif%}
		<div class="col-lg-3 col-md-4 col-sm-6 text-center">
			<div class="card bordesito" style="width: 17rem;">
			  <img class="card-img-top" src="{{Actividad.logo.url}}" alt="{{Actividad.nombre}}" style="height:150px; weight:50px;">
			  <div class="card-block">
			    <h4 class="card-title title-card">{{Actividad.nombre}}</h4>
			    <p class="card-text"><i class="fa fa-bookmark" aria-hidden="true"></i> {{Actividad.categoria}}</p>
			    <p class="card-text">{{Actividad.descripcion|markdown|truncatewords_html:15}}</p>
			    <a href="{{Actividad.get_absolute_url}}" class="btn btn-primary">más información...</a>
			  </div>
			</div>
		</div>
		{% if forloop.counter|divisibleby:4 %}
		</div><br><br><div class="row">
	    {% endif %}            
	    {% if forloop.last %}
	        </div>
	    {% endif %} 
    {%endfor%}
</div>
{%endblock content%}