TeotiShopy/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from home import urls as UrlsHome
from actividades import urls as UrlsActividades
from eventos import urls as UrlsEventos
from alojamiento import urls as UrlsAlojamientos
from blog import urls as UrlsBlog
from restaurantes import urls as UrlsRestaurantes
from servicios import urls as UrlsServicios
from tour import urls as UrlsTour
from shop import urls as UrlsShop
from ruta import urls as UrlsRuta

from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include(UrlsBlog,namespace="blog")),
    url(r'^',include(UrlsHome,namespace="home")),
    url(r'^',include(UrlsEventos,namespace="eventos")),
    url(r'^',include(UrlsActividades,namespace="actividades")),
    url(r'^',include(UrlsAlojamientos,namespace="alojamientos")), 
    url(r'^',include(UrlsRestaurantes,namespace="restaurantes")),
    url(r'^',include(UrlsServicios,namespace="servicios")),
    url(r'^',include(UrlsTour,namespace="tours")),
    url(r'^',include(UrlsShop,namespace="shop")),
    url(r'^',include(UrlsRuta,namespace="ruta")),        
    url(
    	regex=r'^media/(?P<path>.*)$',
    	view=serve,
    	kwargs = {'document_root':settings.MEDIA_ROOT}),
]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.PostList.as_view(), name='post_list'),
	url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.PostList.as_view(), name="post_list_by_tag"),
	url(r'^list/$', views.PostListView.as_view(), name='post_list_view'),
	url(r'^(?P<post>[-\w]+)/$', views.PostDetailView.as_view(), name="post_detail"),
	url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.PostDetail.as_view(), name="post_detail"),
	url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/(?P<ready>\d+)/$', views.PostDetail.as_view(), name="post_detail_ready"),
	url(r'^(?P<post_id>\d+)/share/$', views.SentEmailView.as_view(), name="post_share"),
	url(r'^(?P<post_id>\d+)/(?P<conf>\d+)/share/$', views.SentEmailView.as_view(), name="post_share_conf"),
]

home/urls.py
from django.conf.urls import url
from . import views

urlpatterns =[
	url(r'^$',views.Home.as_view(),name="home"),
	url(r'^tienda/$',views.TiendaView.as_view(),name="tienda"),
	url(r'^prestadores-servicio/$',views.PrestadoresView.as_view(), name = "prestadores"),
	url(r'^sitios-web/$',views.SiteWeb.as_view(), name = "siteweb"),
]

restaurantes/urls.py
from django.conf.urls import url
from . import views

urlpatterns =[
	url(r'^restaurant-list/$',views.Restaurant_List.as_view(), name="restaurant_list"),
	url(r'^restaurant-detail/(?P<slug>[-\w]+)/$',views.Restaurant_Detail.as_view(),name="restaurant_detail"),
	url(r'^restaurant-list/(?P<categoria_slug>[-\w]+)/$',views.Restaurant_List.as_view(),name='restaurantes-list-by-categoria'),
	# url(r'^restaurant-detail/(?P<id>\d+)/$',views.Restaurant_Detail.as_view(), name="restaurant_detail"),
]

restaurantes/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse


class CategoriaRest(models.Model):
	nombre = models.CharField(max_length=250,db_index=True)
	slug = models.CharField(max_length=250,db_index=True,unique=True)

	class Meta():
		ordering = ('nombre',)
		verbose_name='categoria_restaurant'
		verbose_name_plural = 'categorias_restaurant'

	def __str__(self):
		return self.nombre

	def get_absolute_url(self):
		return reverse('restaurantes:restaurantes-list-by-categoria',args=[self.slug])

# Create your models here.
class Restaurant(models.Model):
	categoria = models.ForeignKey(CategoriaRest,related_name='categoria',blank=True,null=True)
	nombre = models.CharField(max_length=100)
	slug = models.SlugField(max_length=100)
	descripcion = models.TextField()
	logo = models.ImageField(upload_to='logo-restaurantes', default='img/teo2.png',blank=True, null=True)
	portada_uno = models.ImageField(upload_to="portadas-restaurantes", default='img/teo2.png',blank=True,null=True)
	portada_dos = models.ImageField(upload_to='portadas-restaurantes', default='img/teo2.png',blank=True,null=True)
	portada_tres = models.ImageField(upload_to='portadas-restaurantes', default='img/teo2.png',blank=True,null=True)
	ubicacion = models.CharField(max_length=300)
	lat = models.FloatField(null=True,blank=True,default=None)
	lng = models.FloatField(null=True,blank=True,default=None)
	telefono_uno = models.CharField(max_length=50)
	telefono_dos = models.CharField(max_length=50, blank=True, null=True)
	paginaWeb = models.CharField(max_length=300)
	correo = models.EmailField(max_length=100, blank=True,null=True,default='contacto@teotihuacanmagico.com.mx')
	facebook = models.URLField(max_length=200, blank=True,null=True,default='https://www.facebook.com/teotihuacanmagicomx/')
	twitter =models.URLField(max_length=200, blank=True,null=True,default='https://www.facebook.com/teotihuacanmagicomx/')
	instagram = models.URLField(max_length=200, blank=True,null=True,default='https://www.facebook.com/teotihuacanmagicomx/')
	youtube = models.URLField(max_length=200, blank=True,null=True,default='https://www.facebook.com/teotihuacanmagicomx/')
	horario = models.CharField(max_length=250)
	menu = models.ImageField(upload_to="menu-restaurant", default='img/teo2.png',blank=True,null=True)
	menu_image = models.ImageField(upload_to = "menu-restaurant" , default = 'img/teo2.png', blank = True, null = True)
	menu_image_uno = models.ImageField(upload_to = "menu-restaurant" , default = 'img/teo2.png', blank = True, null = True)

	def __str__(self):
		return self.nombre

	def get_absolute_url(self):
		return reverse('restaurantes:restaurant_detail',args=[self.slug])

class Marcador(models.Model):
	restaurant = models.ForeignKey(Restaurant, related_name='restaurant')
	nombre = models.CharField(max_length=250, blank=True,null=True)
	latitud = models.FloatField(null=True,blank=True,default=None)
	longitud = models.FloatField(null=True,blank=True,default=None)

	def __str__(self):
		return self.nombre

restaurantes/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from .models import Restaurant,CategoriaRest,Marcador

class Restaurant_List(View):
	def get(self,request,categoria_slug=None):
		template_name = "restaurant_list.html"
		categoria_restaurant = None
		categorias_restaurant = CategoriaRest.objects.all()
		restaurantes = Restaurant.objects.all()
		if categoria_slug:
			categoria_restaurant = get_object_or_404(CategoriaRest,slug=categoria_slug)
			restaurantes = restaurantes.filter(categoria=categoria_restaurant)
		context = {
			'categoria_restaurant':categoria_restaurant,
			'categorias_restaurant':categorias_restaurant,
			'restaurantes':restaurantes,
		}
		return render(request,template_name,context)

class Restaurant_Detail(View):
	def get(self,request,slug):
		template_name = "restaurant_detail.html"
		restaurant = get_object_or_404(Restaurant,slug=slug)
		marcadores = Marcador.objects.all().filter(restaurant = restaurant)
		context = {
			'restaurant':restaurant,
			'marcadores':marcadores,
		}
		return render(request,template_name,context)

restaurantes/templates/restaurant_detail.html
{%extends 'base_detail.html' %}
{% load actividad_tags %}
{% load jsonify %}
{% load static%}

{% block head %}
    <!--Facebook-->
    <!-- You can use open graph tags to customize link previews.
    Learn more: https://developers.facebook.com/docs/sharing/webmasters -->
    <meta property="og:url"           content="http://www.teotihuacanmagico.com.mx{{restaurant.get_absolute_url}}" />
    <meta property="og:type"          content="article" />
    <meta property="og:title"         content="{{ restaurant.nombre }}" />
    <meta property="og:description"   content="{{ restaurant.descripcion}}" />
    <meta property="og:image"         content="{{ restaurant.portada_uno.url}}" />

{% endblock head %}

{% block content%}

<div class="container" style="padding-top:150px;margin-bottom: 0px; background-color: #fafafa">
    <div class="row">
        <div class="col-lg-4">
            <a href="{% url 'restaurantes:restaurant_list' %}"><i class="fa fa-arrow-left" aria-hidden="true"></i> Regresar</a>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-8 text-center">
            <img src="{{restaurant.logo.url}}" class="img-circle" style="width: 300px; height: 250px;">
            <hr>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-8">
            <h2 class="title text-center">{{restaurant.nombre}}</h2>
            <p class="title subtitle text-center">Categoria: {{restaurant.categoria.nombre}}</p>
            <p class="title subtitle text-center">Horario: {{restaurant.horario}}</p>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-12">
            <p class="subtitle title text-center"><i class="fa fa-bolt" aria-hidden="true"></i> Información General</p>
            <!--<p><i class="fa fa-calendar" aria-hidden="true"></i> {{evento.fecha}}h.</p>-->
            <p><i class="fa fa-pencil-square-o" aria-hidden="true"></i> {{restaurant.descripcion|markdown}}.</p>
            <p><i class="fa fa-map-marker" aria-hidden="true"></i> {{restaurant.ubicacion}}.</p>       

            {%if restaurant.telefono_uno%}
            <p><i class="fa fa-whatsapp" aria-hidden="true"></i> {{restaurant.telefono_uno}}</p>
            {%else%}
            <p><i class="fa fa-phone" aria-hidden="true"></i> No Disponible</p>
            {%endif%}

            {%if restaurant.telefono_dos%}
            <p><i class="fa fa-mobile" aria-hidden="true"></i> {{restaurant.telefono_dos}}</p>
            {%else%}
            <p><i class="fa fa-mobile" aria-hidden="true"></i> No Disponible</p>
            {%endif%}

            <p><i class="fa fa-envelope" aria-hidden="true"></i> {{restaurant.correo}}</a></p>
            <p><a href="{{restaurant.paginaWeb}}" style="color:#7e8b8d;" target="_blank"><i class="fa fa-globe" aria-hidden="true"></i> {{restaurant.paginaWeb}}</a></p>
            <hr>
            <div class="container text-center">
                <h2 class="subtitle title text-center">Redes Sociales</h2>
                <div class="row">
                    <div class="col-lg-3 col-sm-3">
                        <p><a href="{{restaurant.facebook}}" style="color:blue;" target="_blank"><i class="fa fa-facebook-square" aria-hidden="true"></i></a></p>
                    </div>
                    <div class="col-lg-3 col-sm-3">
                        <p><a href="{{restaurant.twitter}}" style="color:cornflowerblue;" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a></p>
                    </div>
                    <div class="col-lg-3 col-sm-3">
                        <p><a href="{{restaurant.instagram}}" style="color: rgba-purple-strong;" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a></p>
                    </div>
                    <div class="col-lg-3 col-sm-3">
                        <p><a href="{{restaurant.youtube}}" style="color:red;" target="_blank"><i class="fa fa-youtube" aria-hidden="true"></i></a></p>
                    </div>  
                </div>
            </div>
            <hr>
            <h2 class="subtitle title text-center"><i class="fa fa-map" aria-hidden="true"></i> Mapa</h2>
            <div id='map' style='width:auto; height: 300px;'></div>
            <hr>
              
        </div>
            
        <div class="col-lg-6 col-md-6 col-sm-12">
            <p class="subtitle title text-center"><i class="fa fa-bars" aria-hidden="true"></i> Ménu: <br></p>
            <div class="container" style="padding-top:0px;">
            <!--First row-->
                        <div class="row mb-2 mt-1">
                            
                            <!--Carousel header-->
                            <div class="col-lg-12 col-md-12 col-sm-12"> 

                                <!--Carousel Wrapper-->
                                <div id="teotihuacan-magico-1" class="carousel slide carousel-fade z-depth-1-half" data-ride="carousel">
                                    <!--Indicators-->
                                    <ol class="carousel-indicators">
                                        <li data-target="#teotihuacan-magico-1" data-slide-to="0" class="active"></li>
                                        <li data-target="#teotihuacan-magico-1" data-slide-to="1"></li>
                                        <li data-target="#teotihuacan-magico-1" data-slide-to="2"></li>
                                    </ol>
                                    <!--/.Indicators-->

                                    <!--Slides-->
                                    <div class="carousel-inner" role="listbox">
                                        <!--First slide-->
                                        <div class="carousel-item active">
                                            <a href="#!"><img src="{{restaurant.menu.url}}" alt="{{restaurant.nombre}}" class="img-fluid"></a>
                                        </div>
                                        <!--/First slide-->

                                        <!--Second slide-->
                                        <div class="carousel-item">
                                            <a href="#!"><img src="{{restaurant.menu_image.url}}" alt="{{restaurant.nombre}}" class="img-fluid"></a>
                                        </div>
                                        <!--/Second slide-->

                                        <!--Third slide-->
                                        <div class="carousel-item">
                                            <a href="#!"><img src="{{restaurant.menu_image_uno.url}}" alt="{{restaurant.nombre}}" class="img-fluid"></a>
                                        </div>
                                        <!--/Third slide-->
                                    </div>
                                    <!--/.Slides-->

                                    <!--Controls-->
                                    <a class="carousel-control-prev" href="#teotihuacan-magico-1" role="button" data-slide="prev">
                                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                    <a class="carousel-control-next" href="#teotihuacan-magico-1" role="button" data-slide="next">
                                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                        <span class="sr-only">Next</span>
                                    </a>
                                    <!--/.Controls-->
                                </div>
                                <!--/.Carousel Wrapper-->

                            </div>
                            <!--/Carousel header-->
                            
                        </div>
                        <!--/First row-->
            </div>

            <hr>
            <h2 class="subtitle title text-center"><i class="fa fa-camera" aria-hidden="true"></i> Fotografías</h2>
            <div class="container" style="padding-top:0px;">
            <!--First row-->
                        <div class="row mb-2 mt-1">
                            
                            <!--Carousel header-->
                            <div class="col-lg-12 col-md-12 col-sm-12"> 

                                <!--Carousel Wrapper-->
                                <div id="teotihuacan-magico-2" class="carousel slide carousel-fade z-depth-1-half" data-ride="carousel">
                                    <!--Indicators-->
                                    <ol class="carousel-indicators">
                                        <li data-target="#teotihuacan-magico-2" data-slide-to="0" class="active"></li>
                                        <li data-target="#teotihuacan-magico-2" data-slide-to="1"></li>
                                        <li data-target="#teotihuacan-magico-2" data-slide-to="2"></li>
                                    </ol>
                                    <!--/.Indicators-->

                                    <!--Slides-->
                                    <div class="carousel-inner" role="listbox">
                                        <!--First slide-->
                                        <div class="carousel-item active">
                                            <a href="#!"><img src="{{restaurant.portada_uno.url}}" alt="{{restaurant.nombre}}" class="img-fluid"></a>
                                        </div>
                                        <!--/First slide-->

                                        <!--Second slide-->
                                        <div class="carousel-item">
                                            <a href="#!"><img src="{{restaurant.portada_dos.url}}" alt="{{restaurant.nombre}}" class="img-fluid"></a>
                                        </div>
                                        <!--/Second slide-->

                                        <!--Third slide-->
                                        <div class="carousel-item">
                                            <a href="#!"><img src="{{restaurant.portada_tres.url}}" alt="{{restaurant.nombre}}" class="img-fluid"></a>
                                        </div>
                                        <!--/Third slide-->
                                    </div>
                                    <!--/.Slides-->

                                    <!--Controls-->
                                    <a class="carousel-control-prev" href="#teotihuacan-magico-2" role="button" data-slide="prev">
                                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                    <a class="carousel-control-next" href="#teotihuacan-magico-2" role="button" data-slide="next">
                                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                        <span class="sr-only">Next</span>
                                    </a>
                                    <!--/.Controls-->
                                </div>
                                <!--/.Carousel Wrapper-->

                            </div>
                            <!--/Carousel header-->
                            
                        </div>
                        <!--/First row-->
            </div> 
            <div class="col-lg-12 col-md-12 col-sm-8 text-center">
                <a href="https://api.whatsapp.com/send?phone={{restaurant.telefono_uno}}&text=Me%20gustaría%20hacer%20una%20Reservacion%20en%20{{restaurant.nombre}}%20enviado%20desde%20Teotihuacán%20Mágico" class="btn btn-danger" target="_blank"> Reservación por WhatsApp</a>
            </div>     
        </div>
    </div>
</div>
<script>

      function initMap() {
        var myLatLng = {lat: {{restaurant.lat|jsonify}} , lng: {{restaurant.lng|jsonify}} };

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 14,
          center: myLatLng
        });
        {% for m  in marcadores  %}
          var marker = new google.maps.Marker({
          position:{lat: {{m.latitud|jsonify}} , lng: {{m.longitud|jsonify}} },
          map: map,
          title: '{{m.nombre|jsonify}}'
        });  
        {% endfor %}
        
      }

</script>
<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDtjM5A6W-i81IPpnYzXbwDpRbNJ0iVc0E&callback=initMap">
</script>
{%endblock content%}


{%block scripts%}
    

{%endblock scripts%}

restaurantes/templates/restaurant_list.html
{% extends 'base.html'%}
{% load actividad_tags %}
{% load blog_tags %}
{% load static%}
{% block head%}
	<!--Facebook-->
    <!-- You can use open graph tags to customize link previews.
    Learn more: https://developers.facebook.com/docs/sharing/webmasters -->
    <meta property="og:url"           content="http://www.teotihuacanmagico.com.mx/restaurant-list/" />
    <meta property="og:type"          content="article" />
    <meta property="og:title"         content="Establecimientos de comida en Teotihuacán" />
    <meta property="og:description"   content="Encuentra los mejores establecimientos y disfruta de una experiencia única" />
    <meta property="og:image"         content="http://www.teotihuacanmagico.com.mx/static/img/teo.png" />

{% endblock head%}
{% block header%}
<!-- streak -->
<div class="streak hm-black-strong streak-lg streak-photo view" style="background-image:url({%static 'img/donde_comer.jpg'%})">
		<div class="flex-center mask">
			<ul class="white-text smooth-scroll title">
				<li><h2 class="h2-responsive">¿Dónde comer?</h2></li>
				<li><h5 class="text-center  " data-wow-delay="0.2s">desde restaurantes hasta fondas de comida corrida..</h5></li>

			</ul>
		</div>
</div>
<!-- /.streak -->
{%endblock header%}

{%block content%}
<div class="container text-left">
	<div class="row">
		<div class="col-4 col-sm-4 col-lg-4 col-md-4">
			<a href="{% url 'home:home' %}"><i class="fa fa-arrow-left" aria-hidden="true"></i> Regresar</a>
		</div>
	</div>
</div>

<div class="container text-center">
	<div class="row">
		<div class="col-12 col-sm-12 col-md-12 col-lg-12">	
			<h2 class="title">Categorias</h2>
			<ul class="list-categoria">
				<li {% if not categoria_restaurant  %}{% endif %} id="catego">
					<a href="{% url 'restaurantes:restaurant_list' %}" class="list">Todos</a>
				</li>
				{% for c in categorias_restaurant %}
				<li{% if categoria_restaurant.slug == c.slug %}{% endif %} id="catego">
					<a href="{{c.get_absolute_url}}" class="list">{{c.nombre}}</a>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
</div>
<div class="container" style="padding: 30px;" id="restaurantes">
	<h2 class="text-center title">
		{% if categoria_restaurant %} {{categoria_restaurant.nombre}} {%else%} Todos {% endif %}
	</h2>
	{%for Restaurant in restaurantes%}
	{% if forloop.first %}
		<div class="row" style="padding-top: 3px;">
	{%endif%}		
		<div class="col-lg-3 col-md-4 col-sm-6 text-center">
			<div class="card bordesito" style="width: 15rem;">
			  <img class="card-img-bottom" src="{{Restaurant.portada_uno.url}}" alt="Teotihuacán Mágico" width="50" height="150">
			  <div class="card-block">
			    <h4 class="card-title title-card text-center">{{Restaurant.nombre}}</h4>
			    <p class="card-text text-center"><i class="fa fa-bookmark" aria-hidden="true"></i> {{Restaurant.categoria}}</p>
			    <p class="card-text text-center">{{Restaurant.descripcion|markdown|truncatewords_html:10}}</p>
			    <a href="{{Restaurant.get_absolute_url}}" class="btn btn-primary">más información...</a>
			  </div>
			</div>
		</div>
		{% if forloop.counter|divisibleby:4 %}
		</div><br><br><div class="row">
        {% endif %}            
        {% if forloop.last %}
            </div>
        {% endif %} 
	{%endfor%}
</div>


{%endblock content%}